Added some of the stuff you suggested
Hunter-Raff/e-ReaderCardCreator pull request #8
Opened 2024-02-07 21:16 UTC by a-Beanz

Went ahead and took the time to add the stuff you suggested earlier.

2024-02-07 23:10 UTC, Hunter-Raff requested changes
I appreciate the work! However, there are some changes that need to be made here before merging:

- This code currently cannot build due to the inclusion of a couple hundred copy/pasted lines near the end of `CCC-Frontend.cs`
- I've added comments at various lines within this PR that I think would help. Most importantly, we should probably move handling the dark mode toggle to a helper function in `Common.cs` to reduce repetitive code across forms
- We should rename the created `.txt` file as just `config.txt` and handle toggling through a `darkModePreference` variable within said file. This gives us scalability for more saved config options in the future.
- The size of the main form seems broken; ideally fixed by handling the size dynamically for different resolutions and viewports, but that's beyond the scope of this PR.

2024-02-07 23:10 UTC, HunterRDev commented on AC_e-Reader_Card_Creator/CCC-Frontend.cs
> +        private void menu_View_Click(object sender, EventArgs e)
Remove extraneous empty function

2024-02-07 23:10 UTC, HunterRDev commented on AC_e-Reader_Card_Creator/CCC-Frontend.cs
> +ntains(letter_sender))
Fails to build due to all of this copy/pasted repeated code. Assuming this is a mistake

2024-02-07 23:10 UTC, HunterRDev commented on AC_e-Reader_Card_Creator/CCC-Frontend.cs
> +        private void ApplyDarkMode()
It'd be a good idea to outsource the contents of this function (and `ToggleDarkMode()` ) to a helper function in `References/Common.cs`. This way we don't have to repeat code for each form added.

2024-02-07 23:10 UTC, HunterRDev commented on AC_e-Reader_Card_Creator/Print-Frontend.cs
> +        public class PrintFrontend
A new class shouldn't be necessary

2024-02-07 23:10 UTC, HunterRDev commented on AC_e-Reader_Card_Creator/Print-Frontend.cs
> +        private void ApplyTheme()
Why call this function if all it does is refer to another function later down? 🤔

2024-02-07 23:10 UTC, HunterRDev commented on AC_e-Reader_Card_Creator/Print-Frontend.cs
> +        private void ToggleDarkMode(object sender, EventArgs e)
Repeating a previous comment, but all of this should probably be outsourced to a helper function so we don't have so much repeated copy/pasted code between each `Frontend.cs` form.

2024-02-07 23:10 UTC, Hunter-Raff commented on AC_e-Reader_Card_Creator/CCC-Frontend.cs
> +            string appDataFolderPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "AC e-Reader Card Creator");
I suggest renaming the created directory and file as `e-ReaderCardCreator/config.txt`. Inside `config.txt`, we could have a `darkModePreference:` variable which can be read by the app. This way, we can add other variables to the config file if we add other user-specific settings in the future.

2024-02-08 02:06 UTC, why1116 commented on AC_e-Reader_Card_Creator/CCC-Frontend.cs
> +ntains(letter_sender))
This wasn't on my local copy, interesting.

2024-02-08 02:26 UTC, why1116 commented
All requested changes **SHOULD** be resolved, i may have missed one as I'm tired and haven't slept yet.

2024-02-08 02:27 UTC, why1116 reviewed
All requested changes SHOULD be resolved, i may have missed one as I'm tired and haven't slept yet.

2024-02-08 22:16 UTC, Hunter-Raff commented
I'll review this over the weekend when I get a chance 👍

2024-02-09 01:40 UTC, why1116 commented
Alright, I'll take this time to look and patch any issues i come across/

2025-01-14 23:08 UTC, closed without merging